//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL8VendorPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class co_bln
    {
        public string co_num { get; set; }
        public short co_line { get; set; }
        public string item { get; set; }
        public string cust_item { get; set; }
        public string feat_str { get; set; }
        public decimal blanket_qty { get; set; }
        public Nullable<System.DateTime> eff_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public Nullable<decimal> cont_price { get; set; }
        public string stat { get; set; }
        public Nullable<System.DateTime> promise_date { get; set; }
        public string pricecode { get; set; }
        public string u_m { get; set; }
        public decimal blanket_qty_conv { get; set; }
        public Nullable<decimal> cont_price_conv { get; set; }
        public string ship_site { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string description { get; set; }
        public string config_id { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte InWorkflow { get; set; }
        public byte print_kit_components { get; set; }
        public string non_inv_acct { get; set; }
        public string non_inv_acct_unit1 { get; set; }
        public string non_inv_acct_unit2 { get; set; }
        public string non_inv_acct_unit3 { get; set; }
        public string non_inv_acct_unit4 { get; set; }
        public Nullable<decimal> cost_conv { get; set; }
        public Nullable<short> days_shipped_before_due_date_tolerance { get; set; }
        public Nullable<short> days_shipped_after_due_date_tolerance { get; set; }
        public Nullable<decimal> shipped_over_ordered_qty_tolerance { get; set; }
        public Nullable<decimal> shipped_under_ordered_qty_tolerance { get; set; }
        public string manufacturer_id { get; set; }
        public string manufacturer_item { get; set; }
        public string uf_pref_type { get; set; }
    }
}
