//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL8VendorPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coitem
    {
        public string co_num { get; set; }
        public short co_line { get; set; }
        public short co_release { get; set; }
        public string item { get; set; }
        public decimal qty_ordered { get; set; }
        public decimal qty_ready { get; set; }
        public decimal qty_shipped { get; set; }
        public decimal qty_packed { get; set; }
        public decimal disc { get; set; }
        public decimal cost { get; set; }
        public decimal price { get; set; }
        public string ref_type { get; set; }
        public string ref_num { get; set; }
        public Nullable<short> ref_line_suf { get; set; }
        public Nullable<short> ref_release { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public Nullable<System.DateTime> ship_date { get; set; }
        public decimal brk_qty__1 { get; set; }
        public decimal brk_qty__2 { get; set; }
        public decimal brk_qty__3 { get; set; }
        public decimal brk_qty__4 { get; set; }
        public decimal brk_qty__5 { get; set; }
        public byte reprice { get; set; }
        public string cust_item { get; set; }
        public decimal qty_invoiced { get; set; }
        public decimal qty_returned { get; set; }
        public decimal cgs_total { get; set; }
        public string feat_str { get; set; }
        public string stat { get; set; }
        public string cust_num { get; set; }
        public Nullable<int> cust_seq { get; set; }
        public Nullable<decimal> prg_bill_tot { get; set; }
        public Nullable<decimal> prg_bill_app { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public Nullable<System.DateTime> promise_date { get; set; }
        public string whse { get; set; }
        public string wks_basis { get; set; }
        public Nullable<decimal> wks_value { get; set; }
        public string comm_code { get; set; }
        public string trans_nat { get; set; }
        public string process_ind { get; set; }
        public string delterm { get; set; }
        public Nullable<decimal> unit_weight { get; set; }
        public string origin { get; set; }
        public Nullable<int> cons_num { get; set; }
        public string tax_code1 { get; set; }
        public string tax_code2 { get; set; }
        public Nullable<decimal> export_value { get; set; }
        public string ec_code { get; set; }
        public string transport { get; set; }
        public Nullable<System.DateTime> pick_date { get; set; }
        public string pricecode { get; set; }
        public string u_m { get; set; }
        public decimal qty_ordered_conv { get; set; }
        public decimal price_conv { get; set; }
        public string co_cust_num { get; set; }
        public Nullable<byte> packed { get; set; }
        public Nullable<byte> bol { get; set; }
        public decimal qty_rsvd { get; set; }
        public decimal matl_cost { get; set; }
        public decimal lbr_cost { get; set; }
        public decimal fovhd_cost { get; set; }
        public decimal vovhd_cost { get; set; }
        public decimal out_cost { get; set; }
        public decimal cgs_total_matl { get; set; }
        public decimal cgs_total_lbr { get; set; }
        public decimal cgs_total_fovhd { get; set; }
        public decimal cgs_total_vovhd { get; set; }
        public decimal cgs_total_out { get; set; }
        public decimal cost_conv { get; set; }
        public decimal matl_cost_conv { get; set; }
        public decimal lbr_cost_conv { get; set; }
        public decimal fovhd_cost_conv { get; set; }
        public decimal vovhd_cost_conv { get; set; }
        public decimal out_cost_conv { get; set; }
        public string ship_site { get; set; }
        public Nullable<byte> sync_reqd { get; set; }
        public string co_orig_site { get; set; }
        public string cust_po { get; set; }
        public string rma_num { get; set; }
        public Nullable<short> rma_line { get; set; }
        public Nullable<System.DateTime> projected_date { get; set; }
        public byte consolidate { get; set; }
        public string inv_freq { get; set; }
        public byte summarize { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string description { get; set; }
        public string config_id { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte InWorkflow { get; set; }
        public string rcpt_rqmt { get; set; }
        public string trans_nat_2 { get; set; }
        public decimal suppl_qty_conv_factor { get; set; }
        public byte print_kit_components { get; set; }
        public Nullable<System.DateTime> due_date_day { get; set; }
        public string external_reservation_ref { get; set; }
        public string non_inv_acct { get; set; }
        public string non_inv_acct_unit1 { get; set; }
        public string non_inv_acct_unit2 { get; set; }
        public string non_inv_acct_unit3 { get; set; }
        public string non_inv_acct_unit4 { get; set; }
        public Nullable<short> days_shipped_before_due_date_tolerance { get; set; }
        public Nullable<short> days_shipped_after_due_date_tolerance { get; set; }
        public Nullable<decimal> shipped_over_ordered_qty_tolerance { get; set; }
        public Nullable<decimal> shipped_under_ordered_qty_tolerance { get; set; }
        public Nullable<short> priority { get; set; }
        public byte invoice_hold { get; set; }
        public string manufacturer_id { get; set; }
        public string manufacturer_item { get; set; }
        public string uf_pref_type { get; set; }
        public decimal qty_picked { get; set; }
    }
}
