//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL8VendorPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemwhse
    {
        public string item { get; set; }
        public string whse { get; set; }
        public Nullable<decimal> qty_on_hand { get; set; }
        public Nullable<decimal> qty_alloc_co { get; set; }
        public Nullable<decimal> alloc_trn { get; set; }
        public Nullable<decimal> qty_trans { get; set; }
        public Nullable<decimal> qty_ordered { get; set; }
        public Nullable<decimal> qty_mrb { get; set; }
        public Nullable<decimal> qty_sold_ytd { get; set; }
        public Nullable<decimal> qty_pur_ytd { get; set; }
        public Nullable<decimal> trn_in_ytd { get; set; }
        public Nullable<decimal> trn_out_ytd { get; set; }
        public Nullable<decimal> qty_reorder { get; set; }
        public Nullable<decimal> sales_ytd { get; set; }
        public Nullable<decimal> sales_ptd { get; set; }
        public Nullable<short> cycle_freq { get; set; }
        public Nullable<System.DateTime> last_cycle { get; set; }
        public Nullable<byte> cnt_in_proc { get; set; }
        public Nullable<byte> cycle_flag { get; set; }
        public string cycle_type { get; set; }
        public Nullable<decimal> phy_inv_qty { get; set; }
        public Nullable<System.DateTime> phy_inv_dte { get; set; }
        public Nullable<decimal> qty_wip { get; set; }
        public Nullable<decimal> qty_rsvd_co { get; set; }
        public string replen_po_num { get; set; }
        public string replen_ps_num { get; set; }
        public string replen_trn_num { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte InWorkflow { get; set; }
        public Nullable<decimal> count_sequence { get; set; }
        public Nullable<decimal> last_count_qty_on_hand { get; set; }
        public Nullable<decimal> unit_cost { get; set; }
        public Nullable<decimal> lst_u_cost { get; set; }
        public Nullable<decimal> avg_u_cost { get; set; }
        public Nullable<decimal> asm_setup { get; set; }
        public Nullable<decimal> asm_run { get; set; }
        public Nullable<decimal> asm_matl { get; set; }
        public Nullable<decimal> asm_tool { get; set; }
        public Nullable<decimal> asm_fixture { get; set; }
        public Nullable<decimal> asm_other { get; set; }
        public Nullable<decimal> asm_fixed { get; set; }
        public Nullable<decimal> asm_var { get; set; }
        public Nullable<decimal> asm_outside { get; set; }
        public Nullable<decimal> comp_setup { get; set; }
        public Nullable<decimal> comp_run { get; set; }
        public Nullable<decimal> comp_matl { get; set; }
        public Nullable<decimal> comp_tool { get; set; }
        public Nullable<decimal> comp_fixture { get; set; }
        public Nullable<decimal> comp_other { get; set; }
        public Nullable<decimal> comp_fixed { get; set; }
        public Nullable<decimal> comp_var { get; set; }
        public Nullable<decimal> comp_outside { get; set; }
        public Nullable<decimal> sub_matl { get; set; }
        public Nullable<decimal> cur_u_cost { get; set; }
        public Nullable<decimal> unit_mat_cost { get; set; }
        public Nullable<decimal> unit_duty_cost { get; set; }
        public Nullable<decimal> unit_freight_cost { get; set; }
        public Nullable<decimal> unit_brokerage_cost { get; set; }
        public Nullable<decimal> unit_insurance_cost { get; set; }
        public Nullable<decimal> unit_loc_frt_cost { get; set; }
        public Nullable<decimal> cur_mat_cost { get; set; }
        public Nullable<decimal> cur_duty_cost { get; set; }
        public Nullable<decimal> cur_freight_cost { get; set; }
        public Nullable<decimal> cur_brokerage_cost { get; set; }
        public Nullable<decimal> cur_insurance_cost { get; set; }
        public Nullable<decimal> cur_loc_frt_cost { get; set; }
        public Nullable<decimal> matl_cost { get; set; }
        public Nullable<decimal> lbr_cost { get; set; }
        public Nullable<decimal> fovhd_cost { get; set; }
        public Nullable<decimal> vovhd_cost { get; set; }
        public Nullable<decimal> out_cost { get; set; }
        public Nullable<decimal> cur_matl_cost { get; set; }
        public Nullable<decimal> cur_lbr_cost { get; set; }
        public Nullable<decimal> cur_fovhd_cost { get; set; }
        public Nullable<decimal> cur_vovhd_cost { get; set; }
        public Nullable<decimal> cur_out_cost { get; set; }
        public Nullable<decimal> avg_matl_cost { get; set; }
        public Nullable<decimal> avg_lbr_cost { get; set; }
        public Nullable<decimal> avg_fovhd_cost { get; set; }
        public Nullable<decimal> avg_vovhd_cost { get; set; }
        public Nullable<decimal> avg_out_cost { get; set; }
        public Nullable<decimal> min_consignment_qty { get; set; }
        public Nullable<decimal> max_consignment_qty { get; set; }
        public Nullable<decimal> qty_contained { get; set; }
        public string uf_pref_type { get; set; }
    }
}
