//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL8VendorPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class po
    {
        public string po_num { get; set; }
        public string vend_num { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<decimal> po_cost { get; set; }
        public string ship_code { get; set; }
        public string terms_code { get; set; }
        public string fob { get; set; }
        public Nullable<byte> print_price { get; set; }
        public string vend_order { get; set; }
        public Nullable<decimal> misc_charges { get; set; }
        public Nullable<decimal> sales_tax { get; set; }
        public Nullable<decimal> freight { get; set; }
        public string stat { get; set; }
        public Nullable<System.DateTime> inv_date { get; set; }
        public string inv_num { get; set; }
        public Nullable<System.DateTime> dist_date { get; set; }
        public string type { get; set; }
        public string drop_ship_no { get; set; }
        public Nullable<int> drop_seq { get; set; }
        public Nullable<System.DateTime> eff_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public string ship_addr { get; set; }
        public Nullable<decimal> m_charges_t { get; set; }
        public Nullable<decimal> sales_tax_t { get; set; }
        public Nullable<decimal> freight_t { get; set; }
        public string whse { get; set; }
        public Nullable<decimal> sales_tax_2 { get; set; }
        public Nullable<decimal> sales_tax_t2 { get; set; }
        public string charfld1 { get; set; }
        public string charfld2 { get; set; }
        public string charfld3 { get; set; }
        public Nullable<System.DateTime> datefld { get; set; }
        public Nullable<decimal> decifld1 { get; set; }
        public Nullable<decimal> decifld2 { get; set; }
        public Nullable<decimal> decifld3 { get; set; }
        public Nullable<byte> logifld { get; set; }
        public Nullable<decimal> duty_amt_t { get; set; }
        public Nullable<decimal> duty_amt { get; set; }
        public Nullable<decimal> brokerage_amt { get; set; }
        public Nullable<decimal> brokerage_amt_t { get; set; }
        public string trans_nat { get; set; }
        public string process_ind { get; set; }
        public string delterm { get; set; }
        public string tax_code1 { get; set; }
        public string tax_code2 { get; set; }
        public string frt_tax_code1 { get; set; }
        public string frt_tax_code2 { get; set; }
        public string msc_tax_code1 { get; set; }
        public string msc_tax_code2 { get; set; }
        public Nullable<decimal> prepaid_amt { get; set; }
        public Nullable<decimal> prepaid_t { get; set; }
        public Nullable<decimal> exch_rate { get; set; }
        public Nullable<byte> fixed_rate { get; set; }
        public string freight_vend_num { get; set; }
        public string duty_vend_num { get; set; }
        public string brokerage_vend_num { get; set; }
        public Nullable<decimal> frt_alloc_percent { get; set; }
        public Nullable<decimal> duty_alloc_percent { get; set; }
        public Nullable<decimal> brk_alloc_percent { get; set; }
        public Nullable<decimal> est_freight { get; set; }
        public Nullable<decimal> act_freight { get; set; }
        public Nullable<decimal> est_brokerage { get; set; }
        public Nullable<decimal> act_brokerage { get; set; }
        public Nullable<decimal> est_duty { get; set; }
        public Nullable<decimal> act_duty { get; set; }
        public string duty_alloc_meth { get; set; }
        public string frt_alloc_meth { get; set; }
        public string brk_alloc_meth { get; set; }
        public string duty_alloc_type { get; set; }
        public string frt_alloc_type { get; set; }
        public string brk_alloc_type { get; set; }
        public string vend_lcr_num { get; set; }
        public Nullable<byte> received { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string buyer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte InWorkflow { get; set; }
        public string ins_vend_num { get; set; }
        public Nullable<decimal> ins_alloc_percent { get; set; }
        public string ins_alloc_type { get; set; }
        public Nullable<decimal> est_insurance { get; set; }
        public string ins_alloc_meth { get; set; }
        public Nullable<decimal> act_insurance { get; set; }
        public Nullable<decimal> insurance_amt { get; set; }
        public Nullable<decimal> insurance_amt_t { get; set; }
        public string loc_frt_vend_num { get; set; }
        public Nullable<decimal> loc_frt_alloc_percent { get; set; }
        public string loc_frt_alloc_type { get; set; }
        public Nullable<decimal> est_local_freight { get; set; }
        public string loc_frt_alloc_meth { get; set; }
        public Nullable<decimal> act_local_freight { get; set; }
        public Nullable<decimal> local_freight_amt { get; set; }
        public Nullable<decimal> local_freight_amt_t { get; set; }
        public Nullable<byte> include_tax_in_cost { get; set; }
        public string trans_nat_2 { get; set; }
        public byte contains_only_tax_free_matls { get; set; }
        public string supply_web_po_stat { get; set; }
        public string builder_po_orig_site { get; set; }
        public string builder_po_num { get; set; }
        public byte builder_po_printed { get; set; }
        public byte synchronized_to_bus { get; set; }
        public byte auto_voucher { get; set; }
        public string uf_pref_type { get; set; }
        public byte auto_receive_demanding_site_po { get; set; }
        public byte auto_ship_demanding_site_co { get; set; }
        public string source_site_co_num { get; set; }
    }
}
