//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL8VendorPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class po_bln
    {
        public string po_num { get; set; }
        public short po_line { get; set; }
        public string item { get; set; }
        public string stat { get; set; }
        public Nullable<decimal> blanket_qty { get; set; }
        public Nullable<decimal> item_cost { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public string vend_item { get; set; }
        public Nullable<decimal> plan_cost { get; set; }
        public string non_inv_acct { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public Nullable<System.DateTime> eff_date { get; set; }
        public string item_type { get; set; }
        public string cost_type { get; set; }
        public Nullable<byte> update_costs { get; set; }
        public Nullable<decimal> unit_mat_cost { get; set; }
        public Nullable<decimal> unit_duty_cost { get; set; }
        public Nullable<decimal> unit_freight_cost { get; set; }
        public Nullable<decimal> unit_brokerage_cost { get; set; }
        public string u_m { get; set; }
        public Nullable<decimal> blanket_qty_conv { get; set; }
        public Nullable<decimal> item_cost_conv { get; set; }
        public Nullable<decimal> plan_cost_conv { get; set; }
        public Nullable<decimal> unit_mat_cost_conv { get; set; }
        public Nullable<decimal> unit_duty_cost_conv { get; set; }
        public Nullable<decimal> unit_freight_cost_conv { get; set; }
        public Nullable<decimal> unit_brokerage_cost_conv { get; set; }
        public string non_inv_acct_unit1 { get; set; }
        public string non_inv_acct_unit2 { get; set; }
        public string non_inv_acct_unit3 { get; set; }
        public string non_inv_acct_unit4 { get; set; }
        public string revision { get; set; }
        public string drawing_nbr { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string description { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte InWorkflow { get; set; }
        public Nullable<decimal> unit_insurance_cost { get; set; }
        public Nullable<decimal> unit_insurance_cost_conv { get; set; }
        public Nullable<decimal> unit_loc_frt_cost { get; set; }
        public Nullable<decimal> unit_loc_frt_cost_conv { get; set; }
        public byte preassign_lots { get; set; }
        public byte preassign_serials { get; set; }
        public string manufacturer_id { get; set; }
        public string manufacturer_item { get; set; }
        public string uf_pref_type { get; set; }
    }
}
