//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL8VendorPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class poitem
    {
        public string po_num { get; set; }
        public short po_line { get; set; }
        public short po_release { get; set; }
        public string item { get; set; }
        public string stat { get; set; }
        public Nullable<decimal> qty_ordered { get; set; }
        public Nullable<decimal> qty_received { get; set; }
        public Nullable<decimal> qty_rejected { get; set; }
        public Nullable<decimal> qty_voucher { get; set; }
        public Nullable<decimal> qty_returned { get; set; }
        public Nullable<decimal> item_cost { get; set; }
        public string ref_type { get; set; }
        public string ref_num { get; set; }
        public Nullable<short> ref_line_suf { get; set; }
        public Nullable<short> ref_release { get; set; }
        public System.DateTime due_date { get; set; }
        public Nullable<System.DateTime> rcvd_date { get; set; }
        public string vend_item { get; set; }
        public string root_job { get; set; }
        public Nullable<short> root_suf { get; set; }
        public Nullable<decimal> plan_cost { get; set; }
        public Nullable<decimal> voucher_cost { get; set; }
        public string non_inv_acct { get; set; }
        public string drop_ship_no { get; set; }
        public Nullable<int> drop_seq { get; set; }
        public string ship_addr { get; set; }
        public Nullable<System.DateTime> promise_date { get; set; }
        public Nullable<System.DateTime> release_date { get; set; }
        public string whse { get; set; }
        public string item_type { get; set; }
        public string cost_type { get; set; }
        public string comm_code { get; set; }
        public string trans_nat { get; set; }
        public string process_ind { get; set; }
        public Nullable<decimal> unit_weight { get; set; }
        public string delterm { get; set; }
        public string origin { get; set; }
        public Nullable<int> cons_num { get; set; }
        public Nullable<decimal> unit_mat_cost { get; set; }
        public Nullable<decimal> unit_duty_cost { get; set; }
        public Nullable<decimal> unit_freight_cost { get; set; }
        public Nullable<decimal> unit_brokerage_cost { get; set; }
        public string tax_code1 { get; set; }
        public string tax_code2 { get; set; }
        public Nullable<decimal> export_value { get; set; }
        public string ec_code { get; set; }
        public string transport { get; set; }
        public string req_num { get; set; }
        public Nullable<short> req_line { get; set; }
        public string u_m { get; set; }
        public Nullable<decimal> qty_ordered_conv { get; set; }
        public Nullable<decimal> item_cost_conv { get; set; }
        public Nullable<decimal> plan_cost_conv { get; set; }
        public Nullable<decimal> unit_mat_cost_conv { get; set; }
        public Nullable<decimal> unit_duty_cost_conv { get; set; }
        public Nullable<decimal> unit_freight_cost_conv { get; set; }
        public Nullable<decimal> unit_brokerage_cost_conv { get; set; }
        public string non_inv_acct_unit1 { get; set; }
        public string non_inv_acct_unit2 { get; set; }
        public string non_inv_acct_unit3 { get; set; }
        public string non_inv_acct_unit4 { get; set; }
        public Nullable<byte> lc_override { get; set; }
        public string revision { get; set; }
        public string drawing_nbr { get; set; }
        public string po_vend_num { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string description { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte InWorkflow { get; set; }
        public Nullable<byte> expedited { get; set; }
        public string rcpt_rqmt { get; set; }
        public Nullable<decimal> unit_insurance_cost { get; set; }
        public Nullable<decimal> unit_insurance_cost_conv { get; set; }
        public Nullable<decimal> unit_loc_frt_cost { get; set; }
        public Nullable<decimal> unit_loc_frt_cost_conv { get; set; }
        public string trans_nat_2 { get; set; }
        public decimal suppl_qty_conv_factor { get; set; }
        public byte unlinked_xref { get; set; }
        public Nullable<System.DateTime> due_date_day { get; set; }
        public byte preassign_lots { get; set; }
        public byte preassign_serials { get; set; }
        public string ipr_id { get; set; }
        public Nullable<decimal> ipr_seq { get; set; }
        public string manufacturer_id { get; set; }
        public string manufacturer_item { get; set; }
        public string uf_pref_type { get; set; }
    }
}
