//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL8VendorPortal.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueryDefs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueryDefs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SL8VendorPortal.Models.QueryDefs", typeof(QueryDefs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///  FROM co
        ///  WHERE co_num IN (
        ///	SELECT co_num
        ///	  FROM coitem
        ///	  WHERE whse IN (~p0) AND stat = &apos;~p1&apos;
        ///	  GROUP BY [co_num]
        ///	  HAVING COUNT([co_num]) &gt; 0).
        /// </summary>
        internal static string SelectCOByLineWarehousesAndStatus {
            get {
                return ResourceManager.GetString("SelectCOByLineWarehousesAndStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT co_bln.RowPointer, ObjectNotes.ObjectNoteToken, SpecificNotes.SpecificNoteToken, SpecificNotes.RecordDate AS LastUpdated, SpecificNotes.NoteDesc, SpecificNotes.NoteContent, SpecificNotes.CreatedBy, SpecificNotes.UpdatedBy, NoteHeaders.NoteHeaderToken, NoteHeaders.NoteFlag as IsInternal
        ///FROM co_bln
        ///  INNER JOIN ObjectNotes ON co_bln.RowPointer = ObjectNotes.RefRowPointer
        ///  INNER JOIN NoteHeaders ON ObjectNotes.NoteHeaderToken = NoteHeaders.NoteHeaderToken
        ///  INNER JOIN SpecificNotes ON ObjectNotes. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectCOLineNotes {
            get {
                return ResourceManager.GetString("SelectCOLineNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT coitem.RowPointer, ObjectNotes.ObjectNoteToken, SpecificNotes.SpecificNoteToken, SpecificNotes.RecordDate AS LastUpdated, SpecificNotes.NoteDesc, SpecificNotes.NoteContent, SpecificNotes.CreatedBy, SpecificNotes.UpdatedBy, NoteHeaders.NoteHeaderToken, NoteHeaders.NoteFlag as IsInternal
        ///FROM coitem
        ///  INNER JOIN ObjectNotes ON coitem.RowPointer = ObjectNotes.RefRowPointer
        ///  INNER JOIN NoteHeaders ON ObjectNotes.NoteHeaderToken = NoteHeaders.NoteHeaderToken
        ///  INNER JOIN SpecificNotes ON ObjectNotes. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectCOLineReleaseNotes {
            get {
                return ResourceManager.GetString("SelectCOLineReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *, brk_qty##1 AS [brk_qty__1], brk_qty##2 AS [brk_qty__2], brk_qty##3 AS [brk_qty__3], brk_qty##4 AS [brk_qty__4], brk_qty##5 AS [brk_qty__5]
        ///    FROM coitem
        ///  WHERE whse IN (~p0) AND stat = &apos;~p1&apos;.
        /// </summary>
        internal static string SelectCOLinesByWarehousesAndStatus {
            get {
                return ResourceManager.GetString("SelectCOLinesByWarehousesAndStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *, brk_qty##1 AS [brk_qty__1], brk_qty##2 AS [brk_qty__2], brk_qty##3 AS [brk_qty__3], brk_qty##4 AS [brk_qty__4], brk_qty##5 AS [brk_qty__5]
        ///      FROM coitem
        ///  WHERE whse IN (~p0) AND stat = &apos;~p1&apos; AND co_num = &apos;~p2&apos;.
        /// </summary>
        internal static string SelectCOLinesByWarehousesAndStatusAndOrderNo {
            get {
                return ResourceManager.GetString("SelectCOLinesByWarehousesAndStatusAndOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT co.RowPointer, ObjectNotes.ObjectNoteToken, SpecificNotes.SpecificNoteToken, SpecificNotes.RecordDate AS LastUpdated, SpecificNotes.NoteDesc, SpecificNotes.NoteContent, SpecificNotes.CreatedBy, SpecificNotes.UpdatedBy, NoteHeaders.NoteHeaderToken, NoteHeaders.NoteFlag as IsInternal
        ///FROM co
        ///  INNER JOIN ObjectNotes ON co.RowPointer = ObjectNotes.RefRowPointer
        ///  INNER JOIN NoteHeaders ON ObjectNotes.NoteHeaderToken = NoteHeaders.NoteHeaderToken
        ///  INNER JOIN SpecificNotes ON ObjectNotes.SpecificNote [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectCONotes {
            get {
                return ResourceManager.GetString("SelectCONotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///  FROM co
        ///  WHERE whse IN (~p0) AND stat = &apos;~p1&apos;.
        /// </summary>
        internal static string SelectCustomerOrdersByWarehousesAndStatus {
            get {
                return ResourceManager.GetString("SelectCustomerOrdersByWarehousesAndStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT itemwhse.[item]
        ///      ,itemwhse.[whse]
        ///      ,itemwhse.[qty_on_hand]
        ///      ,itemwhse.[qty_alloc_co]
        ///      ,itemwhse.[alloc_trn]
        ///      ,itemwhse.[qty_trans]
        ///      ,itemwhse.[qty_ordered]
        ///      ,itemwhse.[qty_mrb]
        ///      ,itemwhse.[qty_sold_ytd]
        ///      ,itemwhse.[qty_pur_ytd]
        ///      ,itemwhse.[trn_in_ytd]
        ///      ,itemwhse.[trn_out_ytd]
        ///      ,itemwhse.[qty_reorder]
        ///      ,itemwhse.[sales_ytd]
        ///      ,itemwhse.[sales_ptd]
        ///      ,itemwhse.[cycle_freq]
        ///      ,itemwhse.[last_cycle]
        ///      ,itemw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectItemWhseByWhsesAndPMTCode {
            get {
                return ResourceManager.GetString("SelectItemWhseByWhsesAndPMTCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select RecordDate
        ///FROM SpecificNotes
        ///WHERE SpecificNoteToken = &apos;~p0&apos;.
        /// </summary>
        internal static string SelectNoteTimeStamp {
            get {
                return ResourceManager.GetString("SelectNoteTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///  FROM po
        ///  WHERE po_num IN (
        ///	SELECT po_num
        ///	  FROM poitem
        ///	  WHERE whse IN (~p0) AND stat = &apos;~p1&apos;
        ///	  GROUP BY [po_num]
        ///	  HAVING COUNT([po_num]) &gt; 0).
        /// </summary>
        internal static string SelectPOByLineWarehousesAndStatus {
            get {
                return ResourceManager.GetString("SelectPOByLineWarehousesAndStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT po_bln.RowPointer, ObjectNotes.ObjectNoteToken, SpecificNotes.SpecificNoteToken, SpecificNotes.RecordDate AS LastUpdated, SpecificNotes.NoteDesc, SpecificNotes.NoteContent, SpecificNotes.CreatedBy, SpecificNotes.UpdatedBy, NoteHeaders.NoteHeaderToken, NoteHeaders.NoteFlag as IsInternal
        ///FROM po_bln
        ///  INNER JOIN ObjectNotes ON po_bln.RowPointer = ObjectNotes.RefRowPointer
        ///  INNER JOIN NoteHeaders ON ObjectNotes.NoteHeaderToken = NoteHeaders.NoteHeaderToken
        ///  INNER JOIN SpecificNotes ON ObjectNotes. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectPOLineNotes {
            get {
                return ResourceManager.GetString("SelectPOLineNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT poitem.RowPointer, ObjectNotes.ObjectNoteToken, SpecificNotes.SpecificNoteToken, SpecificNotes.RecordDate AS LastUpdated, SpecificNotes.NoteDesc, SpecificNotes.NoteContent, SpecificNotes.CreatedBy, SpecificNotes.UpdatedBy, NoteHeaders.NoteHeaderToken, NoteHeaders.NoteFlag as IsInternal
        ///FROM poitem
        ///  INNER JOIN ObjectNotes ON poitem.RowPointer = ObjectNotes.RefRowPointer
        ///  INNER JOIN NoteHeaders ON ObjectNotes.NoteHeaderToken = NoteHeaders.NoteHeaderToken
        ///  INNER JOIN SpecificNotes ON ObjectNotes. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectPOLineReleaseNotes {
            get {
                return ResourceManager.GetString("SelectPOLineReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///    FROM poitem
        ///  WHERE whse IN (~p0) AND stat = &apos;~p1&apos;.
        /// </summary>
        internal static string SelectPOLinesByWarehousesAndStatus {
            get {
                return ResourceManager.GetString("SelectPOLinesByWarehousesAndStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///      FROM poitem
        ///  WHERE whse IN (~p0) AND stat = &apos;~p1&apos; AND po_num = &apos;~p2&apos;.
        /// </summary>
        internal static string SelectPOLinesByWarehousesAndStatusAndOrderNo {
            get {
                return ResourceManager.GetString("SelectPOLinesByWarehousesAndStatusAndOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT po.RowPointer, ObjectNotes.ObjectNoteToken, SpecificNotes.SpecificNoteToken, SpecificNotes.RecordDate AS LastUpdated, SpecificNotes.NoteDesc, SpecificNotes.NoteContent, SpecificNotes.CreatedBy, SpecificNotes.UpdatedBy, NoteHeaders.NoteHeaderToken, NoteHeaders.NoteFlag as IsInternal
        ///FROM po
        ///  INNER JOIN ObjectNotes ON po.RowPointer = ObjectNotes.RefRowPointer
        ///  INNER JOIN NoteHeaders ON ObjectNotes.NoteHeaderToken = NoteHeaders.NoteHeaderToken
        ///  INNER JOIN SpecificNotes ON ObjectNotes.SpecificNote [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectPONotes {
            get {
                return ResourceManager.GetString("SelectPONotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///  FROM po
        ///  WHERE whse IN (~p0) AND stat = &apos;~p1&apos;.
        /// </summary>
        internal static string SelectPurchaseOrdersByWarehousesAndStatus {
            get {
                return ResourceManager.GetString("SelectPurchaseOrdersByWarehousesAndStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///  FROM transfer
        ///  WHERE trn_num IN (
        ///  	SELECT trn_num
        ///  	  FROM trnitem
        ///  	  WHERE (to_whse IN (~p0) OR from_whse IN (~p0)) AND stat IN (~p1)
        ///  	  GROUP BY [trn_num]
        ///	  HAVING COUNT([trn_num]) &gt; 0).
        /// </summary>
        internal static string SelectTOByLineToFromWarehousesAndStatuses {
            get {
                return ResourceManager.GetString("SelectTOByLineToFromWarehousesAndStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT trnitem.RowPointer, ObjectNotes.ObjectNoteToken, SpecificNotes.SpecificNoteToken, SpecificNotes.RecordDate AS LastUpdated, SpecificNotes.NoteDesc, SpecificNotes.NoteContent, SpecificNotes.CreatedBy, SpecificNotes.UpdatedBy, NoteHeaders.NoteHeaderToken, NoteHeaders.NoteFlag as IsInternal
        ///FROM trnitem
        ///  INNER JOIN ObjectNotes ON trnitem.RowPointer = ObjectNotes.RefRowPointer
        ///  INNER JOIN NoteHeaders ON ObjectNotes.NoteHeaderToken = NoteHeaders.NoteHeaderToken
        ///  INNER JOIN SpecificNotes ON ObjectNot [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectTOLineNotes {
            get {
                return ResourceManager.GetString("SelectTOLineNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///      FROM trnitem
        ///  WHERE (to_whse IN (~p0) OR from_whse IN (~p0)) AND stat IN (~p1) AND trn_num = &apos;~p2&apos;.
        /// </summary>
        internal static string SelectTOLinesByToFromWhsesAndStatusAndOrderNo {
            get {
                return ResourceManager.GetString("SelectTOLinesByToFromWhsesAndStatusAndOrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT transfer.RowPointer, ObjectNotes.ObjectNoteToken, SpecificNotes.SpecificNoteToken, SpecificNotes.RecordDate AS LastUpdated, SpecificNotes.NoteDesc, SpecificNotes.NoteContent, SpecificNotes.CreatedBy, SpecificNotes.UpdatedBy, NoteHeaders.NoteHeaderToken, NoteHeaders.NoteFlag as IsInternal
        ///FROM transfer
        ///  INNER JOIN ObjectNotes ON transfer.RowPointer = ObjectNotes.RefRowPointer
        ///  INNER JOIN NoteHeaders ON ObjectNotes.NoteHeaderToken = NoteHeaders.NoteHeaderToken
        ///  INNER JOIN SpecificNotes ON Object [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectTONotes {
            get {
                return ResourceManager.GetString("SelectTONotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT *
        ///  FROM transfer
        ///  WHERE to_whse IN (~p0) AND stat IN (~p1).
        /// </summary>
        internal static string SelectTransferOrdersByToWarehousesAndStatus {
            get {
                return ResourceManager.GetString("SelectTransferOrdersByToWarehousesAndStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE SpecificNotes 
        ///SET NoteContent = &apos;~p1&apos;, NoteDesc = &apos;~p2&apos; 
        ///WHERE SpecificNoteToken = &apos;~p0&apos;.
        /// </summary>
        internal static string UpdateNote {
            get {
                return ResourceManager.GetString("UpdateNote", resourceCulture);
            }
        }
    }
}
