//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL8VendorPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SytelineDbEntities : DbContext
    {
        public SytelineDbEntities()
            : base("name=SytelineDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<transfer> transfers { get; set; }
        public DbSet<trnitem> trnitems { get; set; }
        public DbSet<itemwhse> itemwhses { get; set; }
        public DbSet<co> coes { get; set; }
        public DbSet<co_bln> co_bln { get; set; }
        public DbSet<coitem> coitems { get; set; }
        public DbSet<po> poes { get; set; }
        public DbSet<po_bln> po_bln { get; set; }
        public DbSet<poitem> poitems { get; set; }
        public DbSet<whse> whses { get; set; }
        public DbSet<custaddr> custaddrs { get; set; }
        public DbSet<vendaddr> vendaddrs { get; set; }
    }
}
