//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL8VendorPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transfer
    {
        public string trn_num { get; set; }
        public string from_whse { get; set; }
        public string to_whse { get; set; }
        public string stat { get; set; }
        public string ship_code { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<short> qty_packages { get; set; }
        public string from_site { get; set; }
        public string to_site { get; set; }
        public string entered_site { get; set; }
        public string fob_site { get; set; }
        public Nullable<decimal> exch_rate { get; set; }
        public string freight_vendor { get; set; }
        public string duty_vendor { get; set; }
        public string brokerage_vendor { get; set; }
        public Nullable<decimal> frt_alloc_percent { get; set; }
        public Nullable<decimal> duty_alloc_percent { get; set; }
        public Nullable<decimal> brk_alloc_percent { get; set; }
        public Nullable<decimal> est_freight_amt { get; set; }
        public Nullable<decimal> act_freight_amt { get; set; }
        public Nullable<decimal> est_brokerage_amt { get; set; }
        public Nullable<decimal> act_brokerage_amt { get; set; }
        public Nullable<decimal> est_duty_amt { get; set; }
        public Nullable<decimal> act_duty_amt { get; set; }
        public Nullable<decimal> freight_amt_t { get; set; }
        public Nullable<decimal> brokerage_amt_t { get; set; }
        public Nullable<decimal> duty_amt_t { get; set; }
        public string duty_alloc_meth { get; set; }
        public string frt_alloc_meth { get; set; }
        public string brk_alloc_meth { get; set; }
        public string duty_alloc_type { get; set; }
        public string frt_alloc_type { get; set; }
        public string brk_alloc_type { get; set; }
        public string trans_nat { get; set; }
        public string process_ind { get; set; }
        public string delterm { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte InWorkflow { get; set; }
        public string ins_vendor { get; set; }
        public Nullable<decimal> ins_alloc_percent { get; set; }
        public string ins_alloc_type { get; set; }
        public Nullable<decimal> est_insurance_amt { get; set; }
        public string ins_alloc_meth { get; set; }
        public Nullable<decimal> act_insurance_amt { get; set; }
        public Nullable<decimal> insurance_amt_t { get; set; }
        public string loc_frt_vendor { get; set; }
        public Nullable<decimal> loc_frt_alloc_percent { get; set; }
        public string loc_frt_alloc_type { get; set; }
        public Nullable<decimal> est_local_freight_amt { get; set; }
        public string loc_frt_alloc_meth { get; set; }
        public Nullable<decimal> act_local_freight_amt { get; set; }
        public Nullable<decimal> local_freight_amt_t { get; set; }
        public string trans_nat_2 { get; set; }
        public string export_type { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string uf_pref_type { get; set; }
    }
}
