//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL8VendorPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnitem
    {
        public string trn_num { get; set; }
        public short trn_line { get; set; }
        public string stat { get; set; }
        public string item { get; set; }
        public string trn_loc { get; set; }
        public Nullable<System.DateTime> ship_date { get; set; }
        public Nullable<System.DateTime> rcvd_date { get; set; }
        public Nullable<decimal> qty_req { get; set; }
        public Nullable<decimal> qty_shipped { get; set; }
        public Nullable<decimal> qty_received { get; set; }
        public Nullable<decimal> qty_loss { get; set; }
        public Nullable<decimal> unit_cost { get; set; }
        public string frm_ref_type { get; set; }
        public string frm_ref_num { get; set; }
        public Nullable<short> frm_ref_line_suf { get; set; }
        public Nullable<short> frm_ref_release { get; set; }
        public Nullable<decimal> qty_packed { get; set; }
        public Nullable<System.DateTime> pick_date { get; set; }
        public Nullable<decimal> qty_req_conv { get; set; }
        public string u_m { get; set; }
        public Nullable<decimal> matl_cost { get; set; }
        public Nullable<decimal> lbr_cost { get; set; }
        public Nullable<decimal> fovhd_cost { get; set; }
        public Nullable<decimal> vovhd_cost { get; set; }
        public Nullable<decimal> out_cost { get; set; }
        public System.DateTime sch_rcv_date { get; set; }
        public System.DateTime sch_ship_date { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public string pricecode { get; set; }
        public string to_ref_type { get; set; }
        public string to_ref_num { get; set; }
        public Nullable<short> to_ref_line_suf { get; set; }
        public Nullable<short> to_ref_release { get; set; }
        public string from_site { get; set; }
        public string from_whse { get; set; }
        public string to_site { get; set; }
        public string to_whse { get; set; }
        public Nullable<byte> cross_site { get; set; }
        public Nullable<decimal> unit_freight_cost { get; set; }
        public Nullable<decimal> unit_freight_cost_conv { get; set; }
        public Nullable<decimal> unit_brokerage_cost { get; set; }
        public Nullable<decimal> unit_brokerage_cost_conv { get; set; }
        public Nullable<decimal> unit_duty_cost { get; set; }
        public Nullable<decimal> unit_duty_cost_conv { get; set; }
        public Nullable<decimal> unit_mat_cost { get; set; }
        public Nullable<decimal> unit_mat_cost_conv { get; set; }
        public Nullable<decimal> unit_weight { get; set; }
        public Nullable<byte> lc_override { get; set; }
        public Nullable<System.DateTime> projected_date { get; set; }
        public string comm_code { get; set; }
        public string trans_nat { get; set; }
        public string process_ind { get; set; }
        public string delterm { get; set; }
        public string origin { get; set; }
        public Nullable<int> cons_num { get; set; }
        public Nullable<decimal> export_value { get; set; }
        public string ec_code { get; set; }
        public string transport { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte InWorkflow { get; set; }
        public string rcpt_rqmt_q { get; set; }
        public string rcpt_rqmt_c { get; set; }
        public Nullable<decimal> unit_insurance_cost { get; set; }
        public Nullable<decimal> unit_insurance_cost_conv { get; set; }
        public Nullable<decimal> unit_loc_frt_cost { get; set; }
        public Nullable<decimal> unit_loc_frt_cost_conv { get; set; }
        public string trans_nat_2 { get; set; }
        public decimal suppl_qty_conv_factor { get; set; }
        public byte unlinked_xref { get; set; }
        public Nullable<System.DateTime> sch_rcv_date_day { get; set; }
        public Nullable<System.DateTime> sch_ship_date_day { get; set; }
        public byte preassign_lots { get; set; }
        public byte preassign_serials { get; set; }
        public string uf_pref_type { get; set; }
    }
}
