//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SL8VendorPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class whse
    {
        public string whse1 { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string country { get; set; }
        public string contact { get; set; }
        public string phone { get; set; }
        public string fax_num { get; set; }
        public Nullable<byte> phy_inv_flg { get; set; }
        public string cycle_type { get; set; }
        public Nullable<short> cycle_freq { get; set; }
        public Nullable<byte> logifld { get; set; }
        public Nullable<System.DateTime> datefld { get; set; }
        public string addr__1 { get; set; }
        public string addr__2 { get; set; }
        public string addr__3 { get; set; }
        public string addr__4 { get; set; }
        public byte NoteExistsFlag { get; set; }
        public System.DateTime RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public string charfld1 { get; set; }
        public string charfld2 { get; set; }
        public string charfld3 { get; set; }
        public Nullable<decimal> decifld1 { get; set; }
        public Nullable<decimal> decifld2 { get; set; }
        public Nullable<decimal> decifld3 { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public byte InWorkflow { get; set; }
        public string process_ind { get; set; }
        public string trans_nat { get; set; }
        public string trans_nat_2 { get; set; }
        public string delterm { get; set; }
        public string transport { get; set; }
        public string tax_reg_num1 { get; set; }
        public Nullable<byte> dedicated_inventory { get; set; }
        public string consignment_type { get; set; }
        public string cust_num { get; set; }
        public Nullable<int> cust_seq { get; set; }
        public string vend_num { get; set; }
        public string vendor_consignment_loc { get; set; }
        public byte plan_intra_site_transfer { get; set; }
        public short trn_time { get; set; }
        public string uf_pref_type { get; set; }
    }
}
